### ISSUE TITLE
Upload to addons.mozilla.org

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed-screensharing-firefox-addon#1]
The addon should be released as a first version and published to the addons registry (http://addons.mozilla.org/) so we have an reference the url in the Spreed app of users that don't have the installation yet. Also Firefox only supports loading of signed addons (unless the debugging mode is used).

cc @nickvergessen

**Comment by nickvergessen** [comment]
https://addons.mozilla.org/de/firefox/addon/nextcloud-video-calls/

**Comment by jancborchardt** [comment]
@nickvergessen the outgoing link to this repo on that page includes the closing parentheses ) and results in an error. Can you change that?

**Comment by nickvergessen** [comment]
Fixed
