### ISSUE TITLE
Add icon for the addon list

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed-screensharing-firefox-addon#2]
> ![bildschirmfoto vom 2017-01-31 11-30-47](https://cloud.githubusercontent.com/assets/213943/22461243/d1911cda-e7a8-11e6-8281-1c505ebc47d8.png)

@jancborchardt should we just use our logo?

And can you also prepare a screenshot for the addon page itself?

**Comment by jancborchardt** [comment]
Yeah, let’s just use the Nextcloud favicon basically. Also, we should write »Nextcloud Video calls app« as that is how we call it.
