### ISSUE TITLE
Can't add plugin to Firefox

### ISSUE THREAD

**Issue by GregSutcliffe** [nextcloud/spreed-screensharing-firefox-addon#6]
Was taking NC 12 beta1 for a spin, saw that the video app now supports screensharing - excellent! However, it seems it's not actually possible to install this plugin for it on vanilla Firefox - Mozilla is blocking it because it's unsigned, see this screenshot:

![screenshot from 2017-05-08 23-42-42](https://cloud.githubusercontent.com/assets/827786/25828473/3c5900f0-3448-11e7-8348-ea8ffca394e1.png)

Can it be signed? I could probably disable the check with some effort, but not every user is going to do that...

**Comment by Ivansss** [comment]
We decided not to use the add-on for Firefox any more.
Videocalls app just requires Firefox 52 or newer for using the screensharing feature.

**Comment by nickvergessen** [comment]
Adjusted the readme

**Comment by GregSutcliffe** [comment]
Ah perfect, I didn't realise the screenshare option won't appear until in a call, so I went hunting for ideas and ended up here. Thanks for clarifying :)
